import localFont from "next/font/local";
import "./globals.css";
import {
  Noto_Sans_SC,// Noto Sans 简体中文
  Noto_Serif // Noto Serif
} from 'next/font/google';

// 配置 Noto Sans 简体中文
const notoSansSC = Noto_Sans_SC({
  subsets: ['latin'],
  weight: ['400', '500', '700'],// 可用的字重
  display: 'swap',
});

// 如果需要同时使用多个字体，可以这样配置
const notoSerif = Noto_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const clashDisplay = localFont({
  src: "./fonts/ClashDisplay-Variable.woff",
  variable: "--font-clash-display",
  weight: "200 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN" className={`${notoSansSC.className} ${geistMono.variable} ${clashDisplay.variable} antialiased`}>
    <body>{children}</body>
    </html>
  );
}